from django import forms

class DiabetesForm(forms.Form):
    HighBP = forms.IntegerField(min_value=0, max_value=1, label="High Blood Pressure (0/1)")
    HighChol = forms.IntegerField(min_value=0, max_value=1, label="High Cholesterol (0/1)")
    CholCheck = forms.IntegerField(min_value=0, max_value=1, label="Cholesterol Check (0/1)")
    BMI = forms.FloatField(min_value=0, label="BMI")
    Smoker = forms.IntegerField(min_value=0, max_value=1, label="Smoker (0/1)")
    Stroke = forms.IntegerField(min_value=0, max_value=1, label="Stroke (0/1)")
    HeartDiseaseorAttack = forms.IntegerField(min_value=0, max_value=1, label="Heart Disease (0/1)")
    PhysActivity = forms.IntegerField(min_value=0, max_value=1, label="Physical Activity (0/1)")
    Fruits = forms.IntegerField(min_value=0, max_value=1, label="Fruits (0/1)")
    Veggies = forms.IntegerField(min_value=0, max_value=1, label="Veggies (0/1)")
    HvyAlcoholConsump = forms.IntegerField(min_value=0, max_value=1, label="Heavy Alcohol (0/1)")
    AnyHealthcare = forms.IntegerField(min_value=0, max_value=1, label="Healthcare (0/1)")
    NoDocbcCost = forms.IntegerField(min_value=0, max_value=1, label="No Doc Cost (0/1)")
    GenHlth = forms.IntegerField(min_value=1, max_value=5, label="General Health (1-5)")
    MentHlth = forms.IntegerField(min_value=0, max_value=30, label="Mental Health (days)")
    PhysHlth = forms.IntegerField(min_value=0, max_value=30, label="Physical Health (days)")
    DiffWalk = forms.IntegerField(min_value=0, max_value=1, label="Difficulty Walking (0/1)")
    Sex = forms.IntegerField(min_value=0, max_value=1, label="Sex (0=F, 1=M)")
    Age = forms.IntegerField(min_value=1, max_value=13, label="Age Category (1-13)")
    Education = forms.IntegerField(min_value=1, max_value=6, label="Education Level (1-6)")
    Income = forms.IntegerField(min_value=1, max_value=8, label="Income Level (1-8)")